using Microsoft.JSInterop;

namespace ParaglidingFlightLogWeb.Services
{
    public interface ICaptchaManager
    {
        string? SiteKey { get; }

        /// <summary>
        /// Check the captcha response and return a token.
        /// The token can be used with IsCaptchaValid to check if the captcha was valid without having to call the captcha service again. 
        /// This is usefull to work with SSR pages where it is not possible to use interactivity to check the captcha directly on the page
        /// </summary>
        /// <returns></returns>
        Task<string> CheckCaptcha(string challengeResponse);
        /// <summary>
        /// Validates the specified CAPTCHA token and determines whether it represents a successful user challenge.
        /// </summary>
        /// <param name="token">The CAPTCHA token received from the client, typically generated by a CAPTCHA service such as reCAPTCHA.
        /// Cannot be null or empty.</param>
        /// <returns><see langword="true"/> if the token is valid and the CAPTCHA challenge was successfully completed;
        /// otherwise, <see langword="false"/>.</returns>
        bool IsCaptchaValid(string token);
    }
}