name: Deploy Web App

on:
  push:
    tags:
      - 'Release*'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create appsettings.Production.json
        run: echo "${{ secrets.APPSETTINGS_PRODUCTION_JSON }}" > appsettings.Production.json

      - name: Stop current instance
        run: ssh webapp@your-vps-ip 'sudo systemctl stop your-app.service'

      - name: Publish and deploy app
        run: |
          dotnet publish -c Release -o out
          scp -r out/* webapp@your-vps-ip:/path/to/your/app
          scp appsettings.Production.json webapp@your-vps-ip:/path/to/your/app

      - name: Restart app
        run: ssh webapp@your-vps-ip 'sudo systemctl start your-app.service'